[project]
name = "showing-elon-how-productive-i-can-be"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mlflow>=3.8.1",
    "ruff>=0.14.13",
]

[dependency-groups]
dev = [
    "ty>=0.0.12",
]
